# Generated by Django 3.0.2 on 2020-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('second', models.CharField(max_length=100)),
                ('thired', models.CharField(max_length=100)),
                ('fourth', models.CharField(max_length=100)),
                ('fifth', models.CharField(max_length=100)),
            ],
        ),
    ]
