# Generated by Django 3.0.2 on 2020-03-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='list',
        ),
    ]
