# Generated by Django 3.0.2 on 2020-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_info',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
