# Generated by Django 3.0.2 on 2020-03-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked_seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=10)),
                ('plate_no', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('booked_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='bus_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('plate_no', models.CharField(max_length=13, unique=True)),
                ('type', models.CharField(choices=[('AC BUS', 'AC BUS'), ('NON AC BUS', 'NON AC BUS')], default='AC BUS', max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('boarding_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('one', models.BooleanField(default=False)),
                ('two', models.BooleanField(default=False)),
                ('three', models.BooleanField(default=False)),
                ('four', models.BooleanField(default=False)),
                ('five', models.BooleanField(default=False)),
                ('six', models.BooleanField(default=False)),
                ('seven', models.BooleanField(default=False)),
                ('eight', models.BooleanField(default=False)),
                ('nine', models.BooleanField(default=False)),
                ('ten', models.BooleanField(default=False)),
                ('eleven', models.BooleanField(default=False)),
                ('twleve', models.BooleanField(default=False)),
                ('thirteen', models.BooleanField(default=False)),
                ('fourteen', models.BooleanField(default=False)),
                ('fifteen', models.BooleanField(default=False)),
                ('sixteen', models.BooleanField(default=False)),
                ('seventeen', models.BooleanField(default=False)),
                ('eighteen', models.BooleanField(default=False)),
            ],
        ),
    ]
