# Generated by Django 3.0.2 on 2020-03-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_passenger_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger_detail',
            old_name='name',
            new_name='passenger_name',
        ),
    ]
